services:
  - type: web
    name: bppStats
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false

